name: Mezovest Landing Page Deployment

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Test Typescript Code build
      run: |
        npm ci
        npm run build

    - name: Build Code on Remote Server
      uses: appleboy/ssh-action@v0.1.9
      with:
        host: ${{ secrets.HOSTNAME }}
        username: ${{ secrets.USER_NAME }}
        key: ${{ secrets.KEY }}
        port: "22"
        script_stop: true
        script: |
          cd ${{ secrets.PROJECT_PATH }}
          git pull origin main
          yarn && yarn build
